version: "3.7"
services:
    gobot:
        build: ./golang
        container_name: gobot
        env_file: .env
        depends_on: 
            - postgres
    postgres:
        build: ./postgres
        environment:
            - POSTGRES_PASSWORD=postgrespw
            - POSTGRES_USER=postgres
            - POSTGRES_DB=telegram
        hostname: postgresdb
        container_name: postgres
        ports:
            - "5431:5432"
